# Generated by Django 3.0.1 on 2019-12-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CelpeProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(max_length=250, unique=True, verbose_name='Código do projeto')),
                ('is_priority', models.BooleanField(default=False, verbose_name='Prioritário')),
                ('city', models.CharField(max_length=500, verbose_name='cidade')),
                ('invoice_code', models.BigIntegerField(blank=True, null=True, verbose_name='Número da nota fiscal')),
                ('qtd_posts', models.IntegerField(default=0, verbose_name='Quantidade de postes')),
                ('km_dead_wire', models.FloatField(blank=True, default=0, null=True, verbose_name='Quilometragem de linha morta')),
                ('km_live_wire', models.FloatField(blank=True, default=0, null=True, verbose_name='Quilometragem de linha viva')),
                ('start_date', models.DateTimeField(verbose_name='Data de incio')),
                ('finish_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de termino')),
                ('deadline_date', models.DateTimeField(blank=True, null=True, verbose_name='Data prevista')),
                ('instalation_number', models.BigIntegerField(blank=True, null=True, verbose_name='data de instalação')),
                ('invoice_generated', models.BigIntegerField(blank=True, null=True, verbose_name='Nota fiscal gerada')),
                ('barrament_code', models.BigIntegerField(blank=True, null=True, verbose_name='Número do barramento')),
                ('is_service_order', models.BooleanField(default=False, verbose_name='Ordem de Serviço')),
            ],
            options={
                'verbose_name': 'Projeto da Celpe',
                'verbose_name_plural': 'Projetos da Celpe',
                'db_table': 'celpe_projects',
                'ordering': ['id'],
            },
        ),
    ]
