# Generated by Django 3.0.1 on 2019-12-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0002_celpeproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_number', models.CharField(max_length=500, verbose_name='Número do serviço')),
                ('name', models.CharField(max_length=1500, verbose_name='Texto breve')),
                ('description', models.TextField(help_text='Texto longo', verbose_name='Texto longo')),
                ('measurement_unit', models.CharField(max_length=500, verbose_name='Unidade de medida')),
                ('merchandise_group', models.CharField(help_text='Grupo de Mercadoria', max_length=255, verbose_name='Grupo de Mercadoria')),
                ('valuation_class', models.CharField(max_length=500, verbose_name='classe da avaliação')),
                ('tax_rate_code', models.CharField(max_length=500, verbose_name='Código tarifa fiscal')),
                ('service_nature', models.CharField(max_length=500, verbose_name='Natureza do serviço')),
                ('gm_description', models.CharField(max_length=500)),
                ('value', models.FloatField()),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'db_table': 'tasks',
                'ordering': ['name'],
            },
        ),
    ]
