# Generated by Django 3.0.1 on 2019-12-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0004_celpeproject_utd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celpeproject',
            name='qtd_posts',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantidade de postes'),
        ),
        migrations.AlterField(
            model_name='celpeproject',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de incio'),
        ),
    ]
